name: structExpectations-analysis

channels:
  - defaults
  - conda-forge
  - OpenSourceEconomics

dependencies:
  - python=3.7.3
  - pip=19.0.3
  - codecov
  - estimagic
  - matplotlib
  - numba=0.52.0
  - pandas=1.2.0
  - pyaml
  - numpy=1.19.5
  - nlopt
  - pytest
  - pytest-cov
  - Sphinx
  - flake8
  - sphinx-autobuild
  - pip:
    - Py-BOBYQA
    - black
    - pre-commit
    - PyPDF2
