name: structExpectations-analysis

channels:
  - defaults
  - conda-forge
  - OpenSourceEconomics

dependencies:
  - python=3.7.3
  - pip=19.0.3
  - codecov
  - estimagic>=0.0.31
  - matplotlib>=3.0.0
  - numba>=0.43.1
  - pandas>=0.24
  - pyaml
  - numpy
  - pytest
  - pytest-cov
  - Sphinx>=2.0.0
  - flake8
  - sphinx-autobuild
  - pip:
    - black
    - pre-commit
    - PyPDF2
